"""Stage 6 — write results_v2/RESULTS_v2.md and RUN_REPORT.md from the JSON results."""
import json
import os
from pathlib import Path

from config import DATA, RESULTS, ROOT


def jl(path):
    p = Path(path)
    return json.loads(p.read_text()) if p.exists() else None


def f(v, d=3):
    return "—" if v is None else f"{v:.{d}f}"


def table(rows, header):
    return "\n".join(["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"] +
                     ["| " + " | ".join(str(x) for x in r) + " |" for r in rows])


def du(path):
    total = 0
    for root, _, files in os.walk(path):
        for fn in files:
            try:
                total += os.path.getsize(os.path.join(root, fn))
            except OSError:
                pass
    return total


def main():
    L = ["# ACPIA ML v2 — multimodal results", "",
         "Generated by `ml_v2/s6_report.py`. The running application still uses the v1 models; "
         "nothing in `backend/`, `frontend/`, `models/` or `results/` was changed.", ""]

    # ---------------- dataset inventory
    real, syn = du(DATA / "real"), du(DATA / "synthetic")
    L += ["## Dataset", "", table([
        ["Real (downloaded)", f"{real / 1e9:.2f} GB"], ["Synthetic (generated)", f"{syn / 1e9:.2f} GB"],
        ["PAN12 (from v1, real)", f"{du(ROOT / 'data' / 'pan12') / 1e9:.2f} GB"],
        ["Derived text (OCR / Whisper / parsed)", f"{du(DATA / 'derived') / 1e6:.0f} MB"],
        ["**Total**", f"**{(real + syn + du(ROOT / 'data' / 'pan12')) / 1e9:.2f} GB**"]], ["Part", "Size on disk"]), ""]
    sizes = jl(RESULTS / "dataset_sizes_v2.json")
    if sizes:
        L += ["Conversations per split: " + ", ".join(f"{k} {v:,}" for k, v in sizes.items()), ""]
    rt = jl(RESULTS / "conversion_real_text.json")
    if rt:
        L += ["Real text records by source: " + ", ".join(f"{k} {v:,}" for k, v in rt["by_source"].items()), ""]

    # ---------------- conversion quality
    rows = []
    ls = jl(RESULTS / "conversion_librispeech.json")
    if ls and "wer" in ls:
        rows.append(["Whisper on real speech (LibriSpeech test-clean)", f"WER {f(ls['wer'])}", f"{ls['utterances']:,} utterances"])
    v = jl(RESULTS / "conversion_voice_test.json")
    if v and "voice_note_wer" in v:
        rows.append(["Whisper on synthetic voice notes (test pool, fixed transcriber)",
                     f"WER {f(v.get('voice_note_wer'))}", "per conversation"])
    vi = jl(RESULTS / "conversion_video.json")
    if vi:
        rows.append(["Whisper on video audio tracks", f"WER {f(vi.get('video_audio_wer'))}", "whole video"])
    fu = jl(RESULTS / "conversion_funsd.json")
    if fu and "word_cer" in fu:
        rows.append(["EasyOCR on real scanned forms (FUNSD)", f"CER {f(fu['word_cer'])}, word acc {f(fu['word_accuracy'])}",
                     f"{fu['words']:,} words"])
    sc = jl(RESULTS / "conversion_screens.json")
    if sc:
        rows.append(["EasyOCR on chat screenshots", f"CER {f(sc.get('screenshot_cer_mean'))}", "message text"])
    dc = jl(RESULTS / "conversion_documents.json")
    if dc:
        b = dc["exact_message_recovery_rate"].get("B", {})
        rows.append(["PDF / Word text extraction", f"PDF {f(b.get('pdf'))}, Word {f(b.get('docx'))}", "exact message recovery"])
    if rows:
        L += ["## Converting inputs to text", "", table(rows, ["Step", "Quality", "Basis"]), ""]
    hc = jl(RESULTS / "conversion_coco_hashing.json")
    if hc and "summary" in hc:
        L += ["## Image hashing on real photos (COCO)", "",
              table([[h, f(s["match_rate"]), f(s["false_match_rate"], 5), f(s.get("roc_auc"))] for h, s in hc["summary"].items()],
                    ["Hash", "Edited copies matched", "False-match rate", "ROC-AUC"]), ""]

    # ---------------- PAN12 benchmark v2 vs v1
    names = ["distilbert", "ensemble", "tfidf_cnb", "char_lr", "tfidf_lr", "tfidf_svm", "behavioral_hgb"]
    rows = []
    for n in names:
        for ver, folder in (("v2", "results_v2"), ("v1", "results")):
            r = jl(ROOT / folder / f"{n}.json")
            if r:
                m = r["test_final_author_level_PAN12"]
                rows.append([r.get("label", n), ver, f(m["accuracy"], 4), f(m["precision"], 4), f(m["recall"], 4),
                             f(m["f1"], 4), f(m["f0.5"], 4), f(m.get("roc_auc"), 4)])
    if rows:
        L += ["## PAN12 official test set (author level) — v2 vs v1", "",
              table(rows, ["Model", "Ver", "Accuracy", "Precision", "Recall", "F1", "F0.5", "ROC-AUC"]), ""]

    # ---------------- per input type
    mm = jl(RESULTS / "multimodal_eval.json")
    if mm:
        mods = sorted({m for r in mm.values() for m in r["per_input_type"]})
        rows = []
        for key, r in mm.items():
            row = [key]
            for m in mods:
                x = r["per_input_type"].get(m)
                row.append(f"{f(x['at_0.5']['f1'], 2)} / {f(x['at_0.5'].get('roc_auc'), 2)}" if x else "—")
            rows.append(row)
        L += ["## Detection per input type (synthetic pool B, unseen templates)", "",
              "Each cell: F1 at threshold 0.5 / ROC-AUC.", "", table(rows, ["Model"] + mods), ""]
        rows = [[k] + [f(r["per_input_type"].get(m, {}).get("instigator_accuracy"), 2) for m in mods] for k, r in mm.items()]
        L += ["### Instigator identified (stage 2 ranks the adult first)", "", table(rows, ["Model"] + mods), ""]
        srcs = sorted({s for r in mm.values() for s in r["false_alarms_real"]})
        rows = [[k] + [f(r["false_alarms_real"].get(s, {}).get("fpr_at_0.5"), 3) for s in srcs] for k, r in mm.items()]
        L += ["## False alarms on real held-out text (lower is better)", "",
              "Share of ordinary real messages scored ≥ 0.5 as grooming.", "", table(rows, ["Model"] + srcs), ""]

    # ---------------- epochs
    ep = jl(RESULTS / "distilbert_epochs_v2.json")
    if ep:
        L += ["## DistilBERT epochs (validation after every epoch)", "",
              "Stage 1 up to 4 epochs (Devlin et al., 2019, App. A.3); stage 2 up to 20 epochs (Mosbach et al., 2021, §6). "
              "Early stopping on validation F0.5; the best epoch (✓) was kept.", "",
              table([[e["stage"], e["epoch"], f(e["train_loss"], 4), f(e["val_best_f0.5"], 4), f(e["val_pr_auc"], 4),
                      e["seconds"], "✓" if e.get("best") else ""] for e in ep],
                    ["Stage", "Epoch", "Train loss", "Val F0.5", "Val PR-AUC", "Seconds", "Kept"]), ""]

    L += ["## Notes", "",
          "- Synthetic grooming-pattern data is non-explicit and template-based; real grooming data is PAN12 only.",
          "- Real downloaded data (email, SMS, scans, speech, photos) contains no grooming and is used as negatives, "
          "for false-alarm testing, and to measure OCR / speech-to-text / hashing on real inputs.",
          "- Windows Smart App Control blocked the Piper TTS library, so voice notes use the Windows built-in voices "
          "(Microsoft David / Zira at varied speaking rates).",
          "- Known issue in this run: the first voice-note transcription silently dropped a few very short clips, "
          "which misaligned transcripts for about half of the 300 voice-note TRAINING conversations (~0.15% of all "
          "training data). The transcriber was fixed and the voice-note TEST set re-transcribed before evaluation, so "
          "voice results above are valid; retraining with corrected voice training data is a follow-up.",
          "- RVL-CDIP scanned documents were skipped in this run (a missing parquet reader, installed too late).",
          "- These models rank material for human review; they do not determine guilt.", ""]
    (RESULTS / "RESULTS_v2.md").write_text("\n".join(L), encoding="utf-8")
    print("wrote", RESULTS / "RESULTS_v2.md")


if __name__ == "__main__":
    main()
