"""Write results/RESULTS.md from the JSON results, so the write-up can never drift from the numbers.

    ..\\.venv\\Scripts\\python report.py
"""
import json

from common import RESULTS, ROOT

ORDER = ["distilbert", "ensemble", "tfidf_cnb", "tfidf_cnb_aug", "char_lr", "tfidf_lr", "tfidf_lr_aug",
         "tfidf_svm", "behavioral_hgb"]


def load(name):
    p = RESULTS / f"{name}.json"
    return json.loads(p.read_text()) if p.exists() else None


def f(v, d=4):
    return "—" if v is None else f"{v:.{d}f}"


def table(rows, header):
    out = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def main():
    res = {n: load(n) for n in ORDER}
    res = {n: r for n, r in res.items() if r}
    ranked = sorted(res.items(), key=lambda kv: -kv[1]["test_final_author_level_PAN12"]["f0.5"])
    best_name, best = ranked[0]
    bf = best["test_final_author_level_PAN12"]

    lines = [
        "# ACPIA ML Lab — Results",
        "",
        "All numbers are generated by `ml/report.py` from the JSON files in this folder.",
        "Benchmark: **PAN 2012 Sexual Predator Identification**, official test set "
        "(218,702 users, 254 predators). Thresholds tuned on a group-aware validation split, then frozen.",
        "",
        f"**Best model: {best['label']}** — F0.5 {bf['f0.5']:.4f}, precision {bf['precision']:.4f}, "
        f"recall {bf['recall']:.4f} (TP {bf['confusion_matrix']['tp']}, FP {bf['confusion_matrix']['fp']}, "
        f"FN {bf['confusion_matrix']['fn']}).",
        "",
        "## Author level (official PAN12 task)",
        "",
    ]
    rows = []
    for n, r in ranked:
        m = r["test_final_author_level_PAN12"]
        cm = m["confusion_matrix"]
        rows.append([r.get("label", n), f(m["accuracy"]), f(m["precision"]), f(m["recall"]), f(m["f1"]),
                     f"**{f(m['f0.5'])}**", f(m.get("roc_auc")), f(m.get("pr_auc")), cm["tp"], cm["fp"], cm["fn"]])
    lines.append(table(rows, ["Model", "Accuracy", "Precision", "Recall", "F1", "F0.5", "ROC-AUC", "PR-AUC", "TP", "FP", "FN"]))

    for key, title in [("test_stage1_conversation", "Stage 1 — conversation level (at tuned t1)"),
                       ("test_stage2_predator_vs_victim", "Stage 2 — predator vs victim (threshold 0.5)")]:
        lines += ["", f"## {title}", ""]
        rows = []
        for n, r in ranked:
            m = r[key]
            rows.append([r.get("label", n), f(m["accuracy"]), f(m["precision"]), f(m["recall"]), f(m["f1"]),
                         f(m["f0.5"]), f(m.get("roc_auc")), f(m.get("pr_auc"))])
        lines.append(table(rows, ["Model", "Accuracy", "Precision", "Recall", "F1", "F0.5", "ROC-AUC", "PR-AUC"]))

    lines += ["", "## Calibration and cost", ""]
    rows = []
    for n, r in ranked:
        c = r.get("calibration", {})
        rows.append([r.get("label", n), r["thresholds"]["t1_stage1"], r["thresholds"]["t2_stage2"],
                     f(c.get("stage1", {}).get("ece"), 3), f(c.get("stage2", {}).get("ece"), 3),
                     f(r.get("stage1_ms_per_conversation"), 3), r.get("model_size_mb", "—"),
                     r.get("train_seconds", "—"), r.get("device", "—")])
    lines.append(table(rows, ["Model", "t1", "t2", "ECE stage 1", "ECE stage 2", "ms / conversation",
                              "Size (MB)", "Train (s)", "Device"]))

    syn = RESULTS / "synthetic_eval.json"
    if syn.exists():
        s = json.loads(syn.read_text())
        lines += ["", "## Domain shift — synthetic pool B (600 modern-style chats, disjoint templates)", "",
                  s["description"], ""]
        rows = []
        for n, r in s["results"].items():
            lbl = res.get(n, {}).get("label", n)
            m = r["at_0.5"]
            rows.append([lbl, f(m.get("roc_auc"), 3), f(m["precision"], 3), f(m["recall"], 3), f(m["f1"], 3),
                         f(r["at_tuned_t1"]["f1"], 3), f(r["stage2_instigator_accuracy"], 3)])
        lines.append(table(rows, ["Model", "ROC-AUC", "Precision @0.5", "Recall @0.5", "F1 @0.5", "F1 @tuned t1",
                                  "Instigator identified"]))

    h = RESULTS / "hashing.json"
    if h.exists():
        hs = json.loads(h.read_text())
        lines += ["", f"## Hashing lab — {hs['n_images']} synthetic images, 16 edits, threshold {hs['threshold']}/64", ""]
        rows = [[hs["hashes"][k], f(v["overall_match_rate"], 3), f(v["false_match_rate"], 5), f(v.get("roc_auc"), 4)]
                for k, v in hs["summary"].items()]
        lines.append(table(rows, ["Hash", "Edited copies matched", "False-match rate", "ROC-AUC"]))

    gov = ROOT / "data" / "gov" / "gov_stats.json"
    if gov.exists():
        g = json.loads(gov.read_text())
        nat = g["ncrb"]["national"]
        lines += ["", "## Government data", "",
                  "NCRB cyber crimes against children (all India): "
                  + ", ".join(f"{n['year']}: {n['total']:,}" for n in nat)
                  + f". Fitted growth {g['ncrb']['trend']['annual_growth_pct']}%/yr (descriptive).",
                  "",
                  "NCMEC CyberTipline reports attributed to India: "
                  + ", ".join(f"{y['year']}: {y['countries'].get('India', 0):,}" for y in g["ncmec"]["years"]) + "."]

    lines += ["", "## Limitations", "",
              "- PAN12 predators were talking to adult decoys, in English, in the 2000s. Re-validation on "
              "real (sanitised) Kerala case data — including Malayalam and Manglish — is required before any use.",
              "- Threshold tuning rests on 27 validation predators; differences of ~0.02 F0.5 are within noise.",
              "- Synthetic chats are template-generated and far easier than real conversations.",
              "- These models rank material for human review. They do not determine guilt."]
    (RESULTS / "RESULTS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote", RESULTS / "RESULTS.md")


if __name__ == "__main__":
    main()
