"""Write results/RESULTS.md from the JSON results, so the write-up can never drift from the numbers.

    ..\\.venv\\Scripts\\python report.py
"""
import json

from common import RESULTS, ROOT

# key -> (full name for the main table, short name for the other tables)
NAMES = {
    "distilbert": ("DistilBERT (fine-tuned)", "DistilBERT"),
    "ensemble": ("Ensemble (DistilBERT + TF-IDF LR)", "Ensemble"),
    "tfidf_cnb": ("TF-IDF + Complement Naive Bayes", "Complement Naive Bayes"),
    "tfidf_cnb_aug": ("Complement NB + Synthetic", "Complement NB + Synthetic"),
    "char_lr": ("Char n-gram TF-IDF + Logistic Regression", "Char n-gram Logistic Regression"),
    "tfidf_lr_aug": ("TF-IDF Logistic Regression + Synthetic", "Logistic Regression + Synthetic"),
    "tfidf_lr": ("TF-IDF + Logistic Regression", "TF-IDF Logistic Regression"),
    "tfidf_svm": ("TF-IDF + Linear SVM", "Linear SVM"),
    "behavioral_hgb": ("Behavioural Signals + Gradient Boosting", "Behavioural Gradient Boosting"),
}
LONG = {k: v[0] for k, v in NAMES.items()}
SHORT = {k: v[1] for k, v in NAMES.items()}
METRICS = [("accuracy", "Accuracy"), ("precision", "Precision"), ("recall", "Recall"), ("f1", "F1"),
           ("f0.5", "F0.5"), ("roc_auc", "ROC-AUC")]


def load(name, folder=RESULTS):
    p = folder / f"{name}.json"
    return json.loads(p.read_text()) if p.exists() else None


def f(v, d=4):
    return "—" if v is None else f"{v:.{d}f}"


def b(s):
    return f"**{s}**"


def table(rows, header, align=None):
    align = align or ["l"] + ["r"] * (len(header) - 1)
    sep = {"l": ":---", "r": "---:", "c": ":---:"}
    out = ["| " + " | ".join(header) + " |", "| " + " | ".join(sep[a] for a in align) + " |"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def bold_table(items, cols, name_of, key_col, lower_better=(), no_bold=(), first="Model"):
    """items: [(model_key, {col: value})]. Best value per column is bold; the row that is best on
    `key_col` also gets its model name in bold. cols: [(col, header, decimals)]."""
    best = {}
    for c, _, _ in cols:
        if c in no_bold:
            best[c] = None
            continue
        vals = [x[c] for _, x in items if x.get(c) is not None]
        best[c] = (min(vals) if c in lower_better else max(vals)) if vals else None
        if c in lower_better and sum(v == best[c] for v in vals) > 1:
            best[c] = None                                  # a tie on the minimum (e.g. 0.00000) is not a winner
    rows = []
    for k, x in items:
        cells = [b(f(x[c], d)) if x.get(c) is not None and x[c] == best[c] else f(x.get(c), d) for c, _, d in cols]
        name = name_of(k)
        win = key_col in best and x.get(key_col) is not None and x[key_col] == best[key_col]
        rows.append([b(name) if win else name, *cells])
    return table(rows, [first, *[h for _, h, _ in cols]])


def metric_table(res, key, name_of, key_col):
    items = [(n, r[key]) for n, r in res.items()]
    return bold_table(items, [(m, h, 4) for m, h in METRICS], name_of, key_col)


def main():
    res = {n: load(n) for n in NAMES}
    res = {n: r for n, r in res.items() if r}
    res = dict(sorted(res.items(), key=lambda kv: -kv[1]["test_final_author_level_PAN12"]["f0.5"]))
    A = "test_final_author_level_PAN12"
    S1, S2 = "test_stage1_conversation", "test_stage2_predator_vs_victim"
    L = ["# ACPIA ML Lab — Results", "",
         "> Generated by `ml/report.py` from the JSON files in this folder. "
         "Best value in each column is **bold**.", ""]

    # 1 ---------------------------------------------------------------- author level
    L += ["## 1. Author-Level Results — Official PAN12 Task", "",
          "218,702 test users, 254 predators (0.12%). A person is flagged if any of their conversations passes "
          "both tuned thresholds. Sorted by F0.5 — the official PAN12 metric.", "",
          metric_table(res, A, LONG.get, "f0.5"), ""]

    # 2 / 3 ------------------------------------------------------------ stages
    L += ["## 2. Stage 1 — Conversation-Level Detection", "",
          "155,128 test conversations (3,737 contain a predator), scored at each model's strict tuned threshold t1.", "",
          metric_table(res, S1, SHORT.get, "f0.5"), "",
          "## 3. Stage 2 — Predator vs Victim Classification", "",
          "5,624 participants of predator conversations; threshold 0.5.", "",
          metric_table(res, S2, SHORT.get, "f1"), ""]

    # 4 ---------------------------------------------------------------- calibration and cost
    cal = []
    for n, r in res.items():
        c = r.get("calibration", {})
        cal.append((n, {"t1": r["thresholds"]["t1_stage1"], "t2": r["thresholds"]["t2_stage2"],
                        "e1": c.get("stage1", {}).get("ece"), "e2": c.get("stage2", {}).get("ece"),
                        "ms": r.get("stage1_ms_per_conversation"), "mb": r.get("model_size_mb"),
                        "tr": r.get("train_seconds")}))
    L += ["## 4. Calibration, Speed and Model Cost", "",
          "ECE = expected calibration error (lower = predicted probabilities can be trusted). "
          "For ECE, speed, size and training time, lower is better.", "",
          bold_table(cal, [("t1", "t1", 3), ("t2", "t2", 2), ("e1", "Stage 1 ECE", 3), ("e2", "Stage 2 ECE", 3),
                           ("ms", "ms / Conversation", 3), ("mb", "Size (MB)", 2), ("tr", "Train (s)", 0)],
                     SHORT.get, "e1", lower_better={"e1", "e2", "ms", "mb", "tr"}, no_bold={"t1", "t2"}), ""]

    # 5 ---------------------------------------------------------------- domain shift
    syn = load("synthetic_eval")
    if syn:
        items = [(n, {"auc": r["at_0.5"].get("roc_auc"), "p": r["at_0.5"]["precision"], "r": r["at_0.5"]["recall"],
                      "f1": r["at_0.5"]["f1"], "ft": r["at_tuned_t1"]["f1"], "ins": r["stage2_instigator_accuracy"]})
                 for n, r in syn["results"].items()]
        L += ["## 5. Domain Shift — 600 Modern Synthetic Chats", "",
              "150 grooming-pattern and 450 benign chats written from templates no model saw in training.", "",
              bold_table(items, [("auc", "ROC-AUC", 3), ("p", "Precision @0.5", 3), ("r", "Recall @0.5", 3),
                                 ("f1", "F1 @0.5", 3), ("ft", "F1 @ Tuned t1", 3), ("ins", "Instigator Identified", 3)],
                         SHORT.get, "auc"), "",
              "**Reading:** spotting a suspicious *conversation* does not transfer to modern chats (most models are "
              "near chance), but identifying *who is driving it* transfers almost perfectly (94–100%).", ""]

    # 6 ---------------------------------------------------------------- hashing
    h = load("hashing")
    if h:
        label = {"sha256": "SHA-256", "ahash": "Average Hash (aHash)", "dhash": "Difference Hash (dHash)",
                 "phash": "DCT Perceptual Hash (pHash)"}
        items = [(k, {"m": v["overall_match_rate"], "fm": v["false_match_rate"],
                      "auc": v.get("roc_auc") if k != "sha256" else None}) for k, v in h["summary"].items()]
        t = bold_table(items, [("m", "Edited Copies Matched", 3), ("fm", "False-Match Rate", 5),
                               ("auc", "ROC-AUC", 4)], lambda k: label.get(k, k), "", lower_better={"fm"})
        t = t.replace("| Model |", "| Hashing Method |", 1).replace(f"| **{f(0, 5)}** |", f"| {f(0, 5)} |", 1) \
            if sum(1 for _, x in items if x["fm"] == 0) > 1 else t.replace("| Model |", "| Hashing Method |", 1)
        L += ["## 6. Image Hashing Lab", "",
              f"{h['n_images']} benign images, each edited 16 ways (re-compression, resize, crop, rotation, colour, "
              f"overlays). Match = Hamming distance ≤ {h['threshold']} of 64 bits.", "", t, ""]

    # 7 / 8 ------------------------------------------------------------ government data
    gov = ROOT / "data" / "gov" / "gov_stats.json"
    if gov.exists():
        g = json.loads(gov.read_text())
        L += ["## 7. NCRB — Cyber Crimes Against Children in India", "",
              table([[n["year"], f"{n['total']:,}"] for n in g["ncrb"]["national"]], ["Year", "Reported Cases"],
                    ["c", "r"]), "",
              f"**Fitted descriptive growth rate: {g['ncrb']['trend']['annual_growth_pct']}% per year** "
              "(growth partly reflects better reporting).", ""]
        yrs = [(y["year"], y["countries"].get("India", 0)) for y in g["ncmec"]["years"]]
        top = max(v for _, v in yrs)
        L += ["## 8. NCMEC CyberTipline Reports Attributed to India", "",
              table([[y, b(f"{v:,}") if v == top else f"{v:,}"] for y, v in yrs], ["Year", "Reports"], ["c", "r"]), "",
              "2024 is lower partly because NCMEC began bundling duplicate reports.", ""]

    # 9 ---------------------------------------------------------------- key results
    def best(items, lower=False):
        return (min if lower else max)(items, key=lambda kv: kv[1])

    top_n, top = next(iter(res.items()))
    ta = top[A]
    cm = ta["confusion_matrix"]
    rows = [["**Overall author detection**", SHORT[top_n], b(f"F0.5 = {f(ta['f0.5'])}")],
            ["Author precision", SHORT[top_n], b(f"{ta['precision'] * 100:.2f}%")],
            ["Author recall", SHORT[top_n], b(f"{ta['recall'] * 100:.2f}%")],
            ["True predators detected", SHORT[top_n], b(f"{cm['tp']} / {cm['tp'] + cm['fn']}")],
            ["False positives", SHORT[top_n], b(cm["fp"])]]
    for label_, key, m in (("Stage 1 ROC-AUC", S1, "roc_auc"), ("Stage 1 PR-AUC", S1, "pr_auc"),
                           ("Stage 2 F1", S2, "f1"), ("Stage 2 F0.5", S2, "f0.5")):
        n, v = best([(n, r[key].get(m) or 0) for n, r in res.items()])
        rows.append([label_, SHORT[n], b(f(v))])
    n, v = best([(n, x["e1"]) for n, x in cal if x["e1"] is not None], lower=True)
    rows.append(["Best calibration", SHORT[n], b(f"ECE = {f(v, 3)}")])
    n, v = best([(n, x["ms"]) for n, x in cal if x["ms"] is not None], lower=True)
    rows.append(["Fastest inference", SHORT[n], b(f"{f(v, 3)} ms/chat")])
    n, v = best([(n, x["mb"]) for n, x in cal if x["mb"] is not None], lower=True)
    rows.append(["Smallest model", SHORT[n], b(f"{f(v, 2)} MB")])
    if syn:
        n, v = best([(n, r["at_0.5"].get("roc_auc") or 0) for n, r in syn["results"].items()])
        rows.append(["Modern synthetic ROC-AUC", SHORT[n], b(f(v, 3))])
        n, v = best([(n, r["stage2_instigator_accuracy"]) for n, r in syn["results"].items()])
        rows.append(["Modern-chat instigator identification", SHORT[n], b(f"{v * 100:.0f}%")])
    if h:
        n, v = best([(k, s.get("roc_auc") or 0) for k, s in h["summary"].items() if k != "sha256"])
        rows.append(["Hash ROC-AUC", n.replace("hash", "Hash"), b(f(v))])
        n, v = best([(k, s["overall_match_rate"]) for k, s in h["summary"].items()])
        rows.append(["Hash edited-copy matching", n.replace("hash", "Hash"), b(f(v, 3))])
    L += ["## 9. Key Best Results Summary", "", table(rows, ["Area", "Best / Notable Model", "Result"], ["l", "l", "r"]), ""]

    # 10 --------------------------------------------------------------- limitations
    L += ["## 10. Limitations", "",
          table([
              ["PAN12 data age", "Conversations are largely from the 2000s and may not represent modern communication."],
              ["Language limitation", "PAN12 is mainly English; Malayalam and Manglish still require validation."],
              ["Adult decoys", "Predators interacted with adult decoys rather than real children."],
              ["Small validation-positive set", "Thresholds were tuned using only **27 validation predators**, so "
                                                "small F0.5 differences may be noise."],
              ["Synthetic dataset", "Synthetic conversations are template-generated and easier than real-world cases."],
              ["Domain shift", "Strong PAN12 performance does **not automatically transfer** to modern-style "
                               "conversations."],
              ["Human review required", "Models should rank or flag material for investigators; **they do not "
                                        "determine guilt**."],
          ], ["Limitation", "Meaning"], ["l", "l"]), ""]

    (RESULTS / "RESULTS.md").write_text("\n".join(L), encoding="utf-8")
    print("wrote", RESULTS / "RESULTS.md")


if __name__ == "__main__":
    main()
